/*  // Begin auto-generated module export configuration comment block.
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-lora_sdr
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_LORA_SDR_API_H  // Guard against multiple inclusion of the API macro definitions.
#define INCLUDED_LORA_SDR_API_H  // Define the macro so the compiler can detect repeated imports.

#include <gnuradio/attributes.h>  // Pull in GNU Radio attribute macros that control symbol visibility.

#ifdef gnuradio_lora_sdr_EXPORTS  // Check if we are building the library itself to export symbols.
#define LORA_SDR_API __GR_ATTR_EXPORT  // When compiling the module, mark public symbols for export from the shared object.
#else
#define LORA_SDR_API __GR_ATTR_IMPORT  // When consuming the module, mark symbols for import from the shared object.
#endif

#endif /* INCLUDED_LORA_SDR_API_H */  // Close the include guard for the API macros.
