#!/usr/bin/env python3
"""Visualize complex symbol dumps produced by tests.

The script loads a binary file of ``complex64`` samples and plots their real
and imaginary components with ``matplotlib``.  Files such as
``tx_capture.bin`` generated by ``test_end_to_end_file`` can be inspected with
this tool.
"""

from __future__ import annotations

import argparse
import numpy as np
import matplotlib.pyplot as plt


def read_complex64(path: str) -> np.ndarray:
    """Read *path* as an array of complex64 values."""
    try:
        data = np.fromfile(path, dtype=np.complex64)
    except OSError as exc:  # pragma: no cover - thin error wrapper
        raise RuntimeError(f"Could not read '{path}': {exc}") from exc
    if data.size == 0:
        raise RuntimeError(f"File '{path}' contained no complex64 samples")
    return data


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Plot complex symbols from a binary dump"
    )
    parser.add_argument("path", help="Binary file containing complex64 samples")
    parser.add_argument(
        "-o", "--output", help="Save plot to this path instead of showing it"
    )
    parser.add_argument(
        "--limit", type=int, help="Only plot the first N samples"
    )
    args = parser.parse_args(argv)

    samples = read_complex64(args.path)
    if args.limit is not None:
        samples = samples[: args.limit]

    fig, ax = plt.subplots()
    ax.plot(samples.real, label="Real")
    ax.plot(samples.imag, label="Imag")
    ax.set_title("Symbol dump")
    ax.set_xlabel("Sample")
    ax.set_ylabel("Value")
    ax.legend()
    fig.tight_layout()

    if args.output:
        fig.savefig(args.output, dpi=150)
    else:  # pragma: no cover - interactive path
        plt.show()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
